version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: library_postgres_db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_library_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: library_management_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/library_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=your_password
      - JWT_SECRET=defaultSecretKeyForLibraryApiProject2026SecureKey

volumes:
  postgres_library_data:
